-- Migration: Add Join Codes Table for Class Enrollment
-- Purpose: Enable students to join classes using unique codes generated by teachers
-- Date: 2026-01-29

-- ============================================
-- 1. Create Join Codes Table
-- ============================================
CREATE TABLE IF NOT EXISTS class_join_codes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    group_id UUID NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    code VARCHAR(10) UNIQUE NOT NULL,
    max_uses INTEGER DEFAULT 50, -- -1 for unlimited
    current_uses INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    
    CONSTRAINT valid_uses CHECK (current_uses >= 0 AND (max_uses = -1 OR current_uses <= max_uses)),
    CONSTRAINT positive_max_uses CHECK (max_uses = -1 OR max_uses > 0)
);

-- ============================================
-- 2. Create Indexes for Performance
-- ============================================
CREATE INDEX IF NOT EXISTS idx_join_codes_code ON class_join_codes(code);
CREATE INDEX IF NOT EXISTS idx_join_codes_group ON class_join_codes(group_id);
CREATE INDEX IF NOT EXISTS idx_join_codes_active ON class_join_codes(is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_join_codes_expires ON class_join_codes(expires_at DESC) WHERE expires_at IS NOT NULL;

-- ============================================
-- 3. Enable Row Level Security
-- ============================================
ALTER TABLE class_join_codes ENABLE ROW LEVEL SECURITY;

-- ============================================
-- 4. Create RLS Policies
-- ============================================

-- Policy 1: Teachers can view join codes for their classes
CREATE POLICY "Teachers can view join codes for their classes"
    ON class_join_codes FOR SELECT
    TO authenticated
    USING (
        group_id IN (
            SELECT id FROM groups 
            WHERE teacher_id = auth.uid()
        )
    );

-- Policy 2: Teachers can create join codes for their classes
CREATE POLICY "Teachers can create join codes for their classes"
    ON class_join_codes FOR INSERT
    TO authenticated
    WITH CHECK (
        created_by = auth.uid() AND
        group_id IN (
            SELECT id FROM groups 
            WHERE teacher_id = auth.uid()
        )
    );

-- Policy 3: Teachers can update their own join codes
CREATE POLICY "Teachers can update their own join codes"
    ON class_join_codes FOR UPDATE
    TO authenticated
    USING (
        created_by = auth.uid() AND
        group_id IN (
            SELECT id FROM groups 
            WHERE teacher_id = auth.uid()
        )
    )
    WITH CHECK (
        created_by = auth.uid() AND
        group_id IN (
            SELECT id FROM groups 
            WHERE teacher_id = auth.uid()
        )
    );

-- Policy 4: Teachers can delete their own join codes
CREATE POLICY "Teachers can delete their own join codes"
    ON class_join_codes FOR DELETE
    TO authenticated
    USING (
        created_by = auth.uid() AND
        group_id IN (
            SELECT id FROM groups 
            WHERE teacher_id = auth.uid()
        )
    );

-- ============================================
-- 5. Update Groups Table (if not already exists)
-- ============================================
ALTER TABLE groups ADD COLUMN IF NOT EXISTS subject VARCHAR(255);
ALTER TABLE groups ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS max_students INTEGER DEFAULT 50;

-- ============================================
-- 6. Utility Function: Generate Unique Join Code
-- ============================================
CREATE OR REPLACE FUNCTION generate_join_code()
RETURNS VARCHAR(10) AS $$
DECLARE
    code VARCHAR(10);
    exists BOOLEAN;
BEGIN
    LOOP
        -- Generate random 8-character alphanumeric code
        code := UPPER(
            SUBSTR(
                'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
                FLOOR(RANDOM() * 36) + 1,
                1
            ) ||
            SUBSTR(
                'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
                FLOOR(RANDOM() * 36) + 1,
                1
            ) ||
            SUBSTR(
                'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
                FLOOR(RANDOM() * 36) + 1,
                1
            ) ||
            SUBSTR(
                'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
                FLOOR(RANDOM() * 36) + 1,
                1
            ) ||
            SUBSTR(
                'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
                FLOOR(RANDOM() * 36) + 1,
                1
            ) ||
            SUBSTR(
                'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
                FLOOR(RANDOM() * 36) + 1,
                1
            ) ||
            SUBSTR(
                'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
                FLOOR(RANDOM() * 36) + 1,
                1
            ) ||
            SUBSTR(
                'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
                FLOOR(RANDOM() * 36) + 1,
                1
            )
        );
        
        SELECT EXISTS(
            SELECT 1 FROM class_join_codes 
            WHERE code = code
        ) INTO exists;
        
        EXIT WHEN NOT exists;
    END LOOP;
    
    RETURN code;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- 7. Verification Query (optional)
-- ============================================
-- SELECT * FROM class_join_codes;
-- SELECT generate_join_code(); -- Test function
